#!/bin/sh

set -e

ARIB25DIR=/var/cache/arib25-gst-installer/arib25
WORKDIR=/var/cache/arib25-gst-installer
BUILDDIR=/var/cache/arib25-gst-installer/build
CHECKDIR=/var/cache/arib25-gst-installer/check
DEB_HOST_MULTIARCH=`dpkg-architecture -qDEB_HOST_MULTIARCH`

case "$1" in
	configure)
		mkdir -p $WORKDIR
		mkdir -p $BUILDDIR
		mkdir -p $CHECKDIR

		if [ ! -f $WORKDIR/fetch-arib25-source.sh ] ; then
			echo "#!/bin/sh" > $WORKDIR/fetch-arib25-source.sh
			echo 'git clone https://github.com/stz2012/libarib25 $ARIB25DIR' >> $WORKDIR/fetch-arib25-source.sh
		fi

		ARIB25DIR=$ARIB25DIR $SHELL $WORKDIR/fetch-arib25-source.sh
		cp -rfp $ARIB25DIR/* $BUILDDIR

		git clone https://github.com/tokitah/arib25-gst $WORKDIR/arib25-gst
		cp -rfp $WORKDIR/arib25-gst/* $BUILDDIR

		( cd $BUILDDIR && ./configure --libdir=/usr/lib/$DEB_HOST_MULTIARCH --disable-install-libarib25 --disable-install-b25 )
		( cd $BUILDDIR && make )

		( cd $BUILDDIR && make install DESTDIR=$CHECKDIR )
		( cd $CHECKDIR && find ./ -type f | sed 's/^\.//' > $WORKDIR/installed-files )

		( cd $BUILDDIR && make install )

		rm -rf $WORKDIR/arib25-gst
		rm -rf $ARIB25DIR
		rm -rf $CHECKDIR
		rm -rf $BUILDDIR
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
